services:
  - type: web
    name: portfolio1
    env: python
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: python3 manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
    healthCheckPath: /
