# Generated by Django 5.0.1 on 2025-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="forks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="GitHub URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_github_project",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="stars",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
