# Generated by Django 5.0.1 on 2025-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pinned",
            field=models.BooleanField(
                default=False, help_text="Pin this project to the featured section"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
